version: "3"
services:
  krakend:
    image: devopsfaith/krakend:latest
    environment:
      KAFKA_BROKERS: pkc-4yyd6.us-east1.gcp.confluent.cloud:9092
      GOOGLE_APPLICATION_CREDENTIALS: /etc/krakend/credentials.json
    ports:
      - 8080:8080
    volumes:
      - ./krakend:/etc/krakend
  api:
    build:
      context: ./api
    environment:
      KAFKA_BROKERS:
      KAFKA_API_KEY:
      KAFKA_API_SECRET:
      KAFKA_TOPIC: business-objective-1
    ports:
      - 9000:9000
    volumes:
      - ./api:/go/src/app
      - rendezvous-sockets:/sockets
  collector:
    build:
      context: ./collector
    environment:
      KAFKA_BROKERS:
      KAFKA_API_KEY:
      KAFKA_API_SECRET:
      KAFKA_TOPIC: business-objective-1
    volumes:
      - ./collector:/go/src/app
      - rendezvous-sockets:/sockets
    networks:
      - internal
  model:
    image: tutorial-model-1
    ports:
      - 8090:8080
    networks:
      - internal

networks:
  internal:

volumes:
  rendezvous-sockets:
