name: Test and build

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - model-enricher
          - model-executor
          - rendezvous-api
          - rendezvous-collector

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          cd src/${{ matrix.module }}
          go test ./...

  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - model-enricher
          - model-executor
          - rendezvous-api
          - rendezvous-collector

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: concurrentai/concurrentai-core-${{ matrix.module }}
          path: src
          dockerfile: src/${{ matrix.module }}/Dockerfile
          tags: latest
          push: false
